### Create a trip
POST http://localhost:3000/trip
Content-Type: application/json

{
    "owner" : 1,
    "title" : "Big city tour",
    "subtitle" : "a city trip to look around in the city",
    "description" : "We go on a trip through a city, there is a interesting building included",
    "public" : true
}

### JUST FOR TESTING: Get a trip
GET http://localhost:3000/trip/7
Content-Type: application/json

### Get all trips that the user has access to
GET http://localhost:3000/trip/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjQsImlhdCI6MTc0MjU0MTk2NCwiZXhwIjoxNzQyNTU5OTY0fQ.ttlIqUwQc2GRmqt1FmtKbKZxn3sagu8yxXXz6zTgGOA
Content-Type: application/json

### Add a Tripaccess to trip
POST http://localhost:3000/trip/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjQsImlhdCI6MTc0MjU0MTk2NCwiZXhwIjoxNzQyNTU5OTY0fQ.ttlIqUwQc2GRmqt1FmtKbKZxn3sagu8yxXXz6zTgGOA
Content-Type: application/json

{
    "user" : 3,
    "trip": 3,
    "accessLevel": "write"
}


### Get all public trips
GET http://localhost:3000/trip/discover
Content-Type: application/json

### Add a Stage
POST http://localhost:3000/trip/7/newStage
Content-Type: application/json

{
  "title": "Stage 3",
  "picture": "base64encodedimage",
  "description": "This is a new stage",
  "displayRoute": true,
  "cost": 100,
  "start": "2023-10-01T00:00:00Z",
  "end": "2023-10-02T00:00:00Z"
}

### Add a locations to stage
POST http://localhost:3000/trip/3/stages/2/locations
Content-Type: application/json

[
    {
        "name": "Location 1",
        "Lat": -71.0589,
        "Lng": 42.3601
    },
    {
        "name": "Location 2",
        "Lat": -71.0589,
        "Lng": 42.3601
    }
]
