### Create a trip
POST http://localhost:3000/trip
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0MjkxODM3NiwiZXhwIjoxNzQyOTIxOTc2fQ.zuXxaGF1Mz4b4yOVLVLKG7rzd1f4d6P2oseyC_7CPCk
Content-Type: application/json

{
    "title" : "Big city tour",
    "subtitle" : "a city trip to look around in the city",
    "description" : "We go on a trip through a city, there is a interesting building included",
    "public" : true,
    "startDate": "2023-03-25T14:30:00Z"
}


### Create a trip
POST http://localhost:3000/trip
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0MjkxODM3NiwiZXhwIjoxNzQyOTIxOTc2fQ.zuXxaGF1Mz4b4yOVLVLKG7rzd1f4d6P2oseyC_7CPCk
Content-Type: application/json

{
    "title": "new",
    "subtitle": "a city trip to look around in the city",
    "description": "We go on a trip through a city, there is a interesting building included",
    "image": null,
    "public": true,
    "startDate": "2023-03-25T14:30:00.000Z",
    "stages": [
        {
            "index": 1,
            "title": "Stage 3",
            "description": "This is a new stage",
            "displayRoute": true,
            "cost": 100,
            "start": "2023-10-01T00:00:00.000Z",
            "end": "2023-10-02T00:00:00.000Z",
            "day": 1,
            "waypoints": [
                {
                    "index": 1,
                    "name": "Location 35445",
                    "lat": -71.0589,
                    "lng": 42.3601
                },
                {
                    "index": 2,
                    "name": "Location 43543543",
                    "lat": -71.0589,
                    "lng": 42.3601
                }
            ]
        }
    ]
}

### Update a trip
PATCH http://localhost:3000/trip/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0Mjg3MTkwNywiZXhwIjoxNzQyODc1NTA3fQ.nwhlxHNnRdruZdpPl0JgvOddjPXCtQRwbil4WLREjzw
Content-Type: application/json

{
    "description" : "UPDATED DESCRIPTION",
    "public" : false
}

### Get all trips that the user has access to
GET http://localhost:3000/trip/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0MjkwNjIwNywiZXhwIjoxNzQyOTA5ODA3fQ.0TvJwC5eibhp3GI_HtRzo1mJiUlG1FHaH1lyY66AzoQ
Content-Type: application/json

### Add a Tripaccess to trip
POST http://localhost:3000/trip/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0MjkwMTg3MCwiZXhwIjoxNzQyOTA1NDcwfQ.tMACQKjZ84GhuJR3q1bdsRFBA1GNs058SkWe-TvADG8
Content-Type: application/json

{
    "userName" : "ilikeadventure",
    "trip": 1,
    "accessLevel": "write"
}


### delete tripaccess
DELETE http://localhost:3000/trip/access/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0MjkwMTg3MCwiZXhwIjoxNzQyOTA1NDcwfQ.tMACQKjZ84GhuJR3q1bdsRFBA1GNs058SkWe-TvADG8
Content-Type: application/json


### Get all public trips
GET http://localhost:3000/trip/discover
Content-Type: application/json

### Add a Stage
POST http://localhost:3000/trip/2/newStage
Content-Type: application/json

{
  "index" : 1,
  "title": "Stage 3",
  "picture": "base64encodedimage",
  "description": "This is a new stage",
  "displayRoute": true,
  "cost": 100,
  "start": "2023-10-01T00:00:00Z",
  "end": "2023-10-02T00:00:00Z",
  "day" : 1
}

### Add a locations to stage
POST http://localhost:3000/trip/2/stages/4/locations
Content-Type: application/json

[
    {
        "index": 2,
        "name": "Location 43543543",
        "lat": -71.0589,
        "lng": 42.3601
    },
    {
        "index": 1,
        "name": "Location 35445",
        "lat": -71.0589,
        "lng": 42.3601
    }
]

### Delete stage (Is successful when user is owner of trip)
DELETE http://localhost:3000/trip/1/stages/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjEsImlhdCI6MTc0Mjg2MDY4MSwiZXhwIjoxNzQyODY0MjgxfQ.iuPj65OB-WMjO2BIP3MA0uDX5tNUZVz-t2AYWZG9QtM
Accept: application/json

### Delete trip (Is successful when user is owner of trip)
DELETE http://localhost:3000/trip/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsaWtlYWR2ZW50dXJlIiwiaWQiOjQsImlhdCI6MTc0MjgzODUwNywiZXhwIjoxNzQyODQyMTA3fQ.Kq9C-9o3tnr23VAU5n8kEAvwQEB62qWK6_AvAnGTObA
Accept: application/json
